package com.tw.wechat.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tw.wechat.entity.User;

import com.tw.wechat.entity.Tweet;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TWEET".
*/
public class TweetDao extends AbstractDao<Tweet, Long> {

    public static final String TABLENAME = "TWEET";

    /**
     * Properties of entity Tweet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TweetId = new Property(0, Long.class, "tweetId", true, "_id");
        public final static Property PrePosition = new Property(1, int.class, "prePosition", false, "PRE_POSITION");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property SenderID = new Property(3, Long.class, "senderID", false, "SENDER_ID");
    }

    private DaoSession daoSession;


    public TweetDao(DaoConfig config) {
        super(config);
    }
    
    public TweetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TWEET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: tweetId
                "\"PRE_POSITION\" INTEGER NOT NULL ," + // 1: prePosition
                "\"CONTENT\" TEXT," + // 2: content
                "\"SENDER_ID\" INTEGER);"); // 3: senderID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TWEET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Tweet entity) {
        stmt.clearBindings();
 
        Long tweetId = entity.getTweetId();
        if (tweetId != null) {
            stmt.bindLong(1, tweetId);
        }
        stmt.bindLong(2, entity.getPrePosition());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        Long senderID = entity.getSenderID();
        if (senderID != null) {
            stmt.bindLong(4, senderID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Tweet entity) {
        stmt.clearBindings();
 
        Long tweetId = entity.getTweetId();
        if (tweetId != null) {
            stmt.bindLong(1, tweetId);
        }
        stmt.bindLong(2, entity.getPrePosition());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        Long senderID = entity.getSenderID();
        if (senderID != null) {
            stmt.bindLong(4, senderID);
        }
    }

    @Override
    protected final void attachEntity(Tweet entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Tweet readEntity(Cursor cursor, int offset) {
        Tweet entity = new Tweet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // tweetId
            cursor.getInt(offset + 1), // prePosition
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // senderID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Tweet entity, int offset) {
        entity.setTweetId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPrePosition(cursor.getInt(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSenderID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Tweet entity, long rowId) {
        entity.setTweetId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Tweet entity) {
        if(entity != null) {
            return entity.getTweetId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Tweet entity) {
        return entity.getTweetId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM TWEET T");
            builder.append(" LEFT JOIN USER T0 ON T.\"SENDER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Tweet loadCurrentDeep(Cursor cursor, boolean lock) {
        Tweet entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User sender = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setSender(sender);

        return entity;    
    }

    public Tweet loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Tweet> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Tweet> list = new ArrayList<Tweet>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Tweet> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Tweet> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
